"""gen_pixel_css.py - generate the pixel-mode overrides for every bitmap url() in the stylesheets.

Pixel mode uses no legacy bitmaps. For every CSS rule (and @keyframes block) in
src/styles/bitmap_ui.css and in the inline <style> of index.html that references
assets/..., emit the same selector with only the url()-bearing declarations, each
url(...) replaced by var(--pxa-<slug>, none):

- icons the art registry can draw (src/pixel/art_registry.js) get that variable set
  at boot to a data URL of the code-drawn pixel art;
- frames / panels / plates resolve to `none` and are restyled by the shared pixel
  components in src/styles/pixel_theme.css.

index.html links the result right after bitmap_ui.css with media="not all"; the <head>
art-mode script flips it to "all" in pixel mode, so the overrides win by source order
without raising specificity. Also writes src/data/pixel_css_art_paths.js (the asset paths
referenced from CSS, for the boot-time variable install).

    python tools/pixel_art/gen_pixel_css.py [--check]
"""
from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'src', 'styles', 'pixel_assets.css')
OUT_JS = os.path.join(ROOT, 'src', 'data', 'pixel_css_art_paths.js')

URL_RE = re.compile(r"""url\(\s*(['"]?)([^'")]+)\1\s*\)""")


def slug(rel: str) -> str:
    return re.sub(r'[^a-zA-Z0-9]+', '-', os.path.splitext(rel)[0]).strip('-')


def parse_blocks(css):
    """Tiny brace parser -> list of (prelude, body, children). Comments stripped."""
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    out = []
    i, n = 0, len(css)
    while i < n:
        j = css.find('{', i)
        if j < 0:
            break
        prelude = css[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth:
            if css[k] == '{':
                depth += 1
            elif css[k] == '}':
                depth -= 1
            k += 1
        body = css[j + 1:k - 1]
        if ';' in prelude:
            prelude = prelude.rsplit(';', 1)[-1].strip()
        if prelude.startswith('@media') or prelude.startswith('@supports'):
            out.append((prelude, None, parse_blocks(body)))
        else:
            out.append((prelude, body, None))
        i = k
    return out


def split_decls(body):
    decls, depth, cur = [], 0, []
    for ch in body:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ';' and depth == 0:
            decls.append(''.join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if ''.join(cur).strip():
        decls.append(''.join(cur).strip())
    return [d for d in decls if d]


def rewrite_value(value, used):
    changed = False

    def sub(m):
        nonlocal changed
        url = m.group(2)
        idx = url.find('assets/')
        if idx < 0 or url.startswith('data:'):
            return m.group(0)
        rel = url[idx + len('assets/'):].split('?')[0].split('#')[0]
        if rel.lower().endswith('.svg'):
            return m.group(0)  # 矢量线稿（药剂炼成面板的示意图）保留原样：功能性图形，不是旧位图材质
        changed = True
        used.add(rel)
        return f'var(--pxa-{slug(rel)}, none)'

    return URL_RE.sub(sub, value), changed


def emit(blocks, used, indent=''):
    lines = []
    for prelude, body, children in blocks:
        if children is not None:
            inner = emit(children, used, indent + '    ')
            if inner:
                lines.append(f'{indent}{prelude} {{')
                lines.extend(inner)
                lines.append(f'{indent}}}')
            continue
        if prelude.startswith('@keyframes') or prelude.startswith('@-webkit-keyframes'):
            new, changed = rewrite_value(body, used)
            if changed:
                body_lines = [ln.rstrip() for ln in new.strip().splitlines() if ln.strip()]
                lines.append(f'{indent}{prelude} {{')
                lines.extend(f'{indent}    {ln.strip()}' for ln in body_lines)
                lines.append(f'{indent}}}')
            continue
        if prelude.startswith('@'):
            continue
        kept = []
        for d in split_decls(body):
            if 'url(' not in d:
                continue
            new, changed = rewrite_value(d, used)
            if changed:
                kept.append(new)
        if kept:
            sel = ' '.join(prelude.split())
            lines.append(f'{indent}{sel} {{')
            lines.extend(f'{indent}    {d};' for d in kept)
            lines.append(f'{indent}}}')
    return lines


def inline_styles(html):
    return re.findall(r'<style[^>]*>(.*?)</style>', html, flags=re.S)


def build():
    used = set()
    parts = [
        '/* AUTO-GENERATED by tools/pixel_art/gen_pixel_css.py - do not edit by hand.',
        ' * Pixel-art mode: same selectors as the bitmap stylesheets; every url(assets/...) becomes',
        ' * var(--pxa-<slug>, none). Icons get the variable at boot (code-drawn pixel art, see',
        ' * src/pixel/art_registry.js); frames/panels stay none and are restyled in pixel_theme.css. */',
        '',
        '/* ---- from index.html <style> ---- */',
    ]
    with open(os.path.join(ROOT, 'index.html'), encoding='utf-8') as fh:
        html = fh.read()
    for css in inline_styles(html):
        parts += emit(parse_blocks(css), used)
    parts += ['', '/* ---- from src/styles/bitmap_ui.css ---- */']
    with open(os.path.join(ROOT, 'src', 'styles', 'bitmap_ui.css'), encoding='utf-8') as fh:
        parts += emit(parse_blocks(fh.read()), used)
    css = '\n'.join(parts) + '\n'
    js = '\n'.join([
        '// AUTO-GENERATED by tools/pixel_art/gen_pixel_css.py - do not edit by hand.',
        '// assets/ 下被样式表 url() 引用的路径；像素模式启动时为其中「图标类」设置 --pxa-<slug> 变量。',
        'export const PIXEL_CSS_ART_PATHS = Object.freeze([',
        *[f"    '{rel}'," for rel in sorted(used)],
        ']);',
        '',
        '/** 与 gen_pixel_css.py 的 slug() 一致 */',
        'export function pixelCssVarName(rel) {',
        "    return `--pxa-${rel.replace(/\\.[^.]+$/, '').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '')}`;",
        '}',
        '',
    ])
    return css, js


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    css, js = build()
    if args.check:
        cur_css = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        cur_js = open(OUT_JS, encoding='utf-8').read() if os.path.exists(OUT_JS) else ''
        if cur_css != css or cur_js != js:
            print('pixel_assets.css / pixel_css_art_paths.js are stale; run tools/pixel_art/gen_pixel_css.py')
            sys.exit(1)
        print('pixel_assets.css up to date')
        return
    for path, text in ((OUT, css), (OUT_JS, js)):
        with open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(text)
        with open(path, encoding='utf-8') as fh:
            assert fh.read() == text, path
    print(f'wrote {OUT} ({css.count("{")} blocks, {css.count("var(--pxa-")} urls) and {OUT_JS}')


if __name__ == '__main__':
    main()
