"""gen_palette_css.py - map every Tailwind colour utility used by the game onto the pixel palette.

The DOM UI mixes ~20 Tailwind colour families (cyan titles, emerald toggles, purple prices,
blue chips...) that have nothing to do with the pixel art palette. In pixel mode each colour
utility is remapped to the nearest semantic ramp of src/pixel/palette.js:

    slate/gray/zinc/neutral/stone -> slate    red/rose -> blood     pink/fuchsia -> rose
    orange -> fire     amber -> brass     yellow -> volt     lime/green -> venom
    emerald/teal -> mint     cyan -> cyan     sky/blue -> ice     indigo/violet/purple -> arcane

Tailwind shade 50..950 maps linearly onto the ramp (light -> dark). Opacity modifiers
(bg-slate-900/80) keep their alpha. Decorative gradients (bg-gradient-to-*) are flattened to
the from- colour; gradient-clipped text gets the from- colour as a solid fill.

Output: src/styles/pixel_palette.css (all rules scoped to html.art-pixel; bitmap mode untouched).

    python tools/pixel_art/gen_palette_css.py [--check]
"""
from __future__ import annotations

import argparse
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'src', 'styles', 'pixel_palette.css')
PALETTE_JS = os.path.join(ROOT, 'src', 'pixel', 'palette.js')

FAMILY = {
    'slate': 'slate', 'gray': 'slate', 'zinc': 'slate', 'neutral': 'slate', 'stone': 'slate',
    'red': 'blood', 'rose': 'blood', 'pink': 'rose', 'fuchsia': 'rose',
    'orange': 'fire', 'amber': 'brass', 'yellow': 'volt', 'lime': 'venom', 'green': 'venom',
    'emerald': 'mint', 'teal': 'mint', 'cyan': 'cyan', 'sky': 'ice', 'blue': 'ice',
    'indigo': 'arcane', 'violet': 'arcane', 'purple': 'arcane',
}
SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]
PROPS = {
    'text': 'color',
    'bg': 'background-color',
    'border': 'border-color',
    'border-t': 'border-top-color',
    'border-b': 'border-bottom-color',
    'border-l': 'border-left-color',
    'border-r': 'border-right-color',
    'from': None,  # 渐变起点：单独处理
}
VARIANTS = {'': '', 'hover:': ':hover', 'focus:': ':focus', 'active:': ':active'}

CLASS_RE = re.compile(
    r'(?<![\w:-])((?:hover:|focus:|active:)?)'
    r'(text|bg|border(?:-[tblr])?|from)-'
    r'(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose|white|black)'
    r'(?:-(50|100|200|300|400|500|600|700|800|900|950))?'
    r'(?:/(\d{1,3}))?(?![\w-])'
)


def load_ramps():
    src = open(PALETTE_JS, encoding='utf-8').read()
    ramps = {}
    for name, body in re.findall(r"^\s*(\w+):\s*\[([^\]]+)\]", src, flags=re.M):
        cols = re.findall(r"'(#[0-9a-fA-F]{6})'", body)
        if cols:
            ramps[name] = cols
    ink = re.search(r"INK\s*=\s*'(#[0-9a-fA-F]{6})'", src).group(1)
    return ramps, ink


def colour(ramps, ink, fam, shade, alpha):
    if fam == 'white':
        hexv = ramps['slate'][-1]
    elif fam == 'black':
        hexv = ink
    else:
        if shade is None:
            return None
        r = ramps[FAMILY[fam]]
        k = SHADES.index(int(shade))
        # 50 → 最亮端，950 → 最暗端
        idx = round((1 - k / (len(SHADES) - 1)) * (len(r) - 1))
        hexv = r[max(0, min(len(r) - 1, idx))]
    if alpha is None:
        return hexv
    a = max(0, min(100, int(alpha))) / 100
    rr, gg, bb = int(hexv[1:3], 16), int(hexv[3:5], 16), int(hexv[5:7], 16)
    return f'rgba({rr},{gg},{bb},{a:g})'


def esc(cls):
    return re.sub(r'([:/.\[\]])', r'\\\1', cls)


def collect():
    texts = [open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()]
    for dp, dns, fs in os.walk(os.path.join(ROOT, 'src')):
        dns[:] = [d for d in dns if d not in ('world_sim',)]
        for f in fs:
            if f.endswith('.js'):
                texts.append(open(os.path.join(dp, f), encoding='utf-8').read())
    found = set()
    for t in texts:
        for m in CLASS_RE.finditer(t):
            found.add(m.groups())
    return sorted(found, key=lambda g: (g[1], g[2], int(g[3] or 0), g[0], g[4] or ''))


def build():
    ramps, ink = load_ramps()
    lines = [
        '/* AUTO-GENERATED by tools/pixel_art/gen_palette_css.py - do not edit by hand.',
        ' * Pixel mode: Tailwind colour utilities used by the game, remapped onto the pixel palette',
        ' * (src/pixel/palette.js). Bitmap mode is untouched (every rule is scoped to html.art-pixel). */',
        '',
        '/* 装饰渐变压平为纯色（起点色）；渐变裁切文字改为起点色实心字 */',
        'html.art-pixel [class*="bg-gradient-to-"] { background-image: none !important; }',
        'html.art-pixel .bg-clip-text { -webkit-background-clip: border-box !important; background-clip: border-box !important;'
        ' background-image: none !important; background-color: transparent !important;'
        ' color: var(--px-grad-text, #efc75a) !important; -webkit-text-fill-color: var(--px-grad-text, #efc75a) !important; }',
        '',
    ]
    n = 0
    for variant, prop, fam, shade, alpha in collect():
        c = colour(ramps, ink, fam, shade, alpha)
        if c is None:
            continue
        cls = f'{variant}{prop}-{fam}' + (f'-{shade}' if shade else '') + (f'/{alpha}' if alpha else '')
        sel = f'html.art-pixel .{esc(cls)}{VARIANTS[variant]}'
        if prop == 'from':
            lines.append(f'{sel} {{ --px-grad-text: {c}; }}')
            lines.append(f'html.art-pixel [class*="bg-gradient-to-"].{esc(cls)}{VARIANTS[variant]} {{ background-color: {c} !important; }}')
        else:
            lines.append(f'{sel} {{ {PROPS[prop]}: {c} !important; }}')
        n += 1
    return '\n'.join(lines) + '\n', n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    text, n = build()
    if args.check:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != text:
            print('pixel_palette.css is stale; run tools/pixel_art/gen_palette_css.py')
            sys.exit(1)
        print('pixel_palette.css up to date')
        return
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    with open(OUT, encoding='utf-8') as fh:
        assert fh.read() == text
    print(f'wrote {OUT} ({n} utilities)')


if __name__ == '__main__':
    main()
